### ISSUE TITLE
Script to match grid points to cities and countries

### ISSUE THREAD

**Issue by oremnirv** [michellewl/building_resilience#2]
Who wants to help to write code for matching grid points (lat/lon) to cities and countries?

**Comment by oremnirv** [comment]
I tested it and it works! :) I also changed the documentation of the function a bit.

Things still to do: 
- Add a description how to pip install the reverse_geocoder package 
- More importantly, test if it works with the data I provided in the drive folder

**Comment by tudor-suciu** [comment]
+ updated information
+ checked with climate data = works

Issue closed

**Comment by tudor-suciu** [comment]
OK, now it is done for sure.
