### ISSUE TITLE
Add # days in a month for Michelle's model  -  March is over 10% longer than February

### ISSUE THREAD

**Issue by oremnirv** [michellewl/building_resilience#30]

**Comment by michellewl** [comment]
I'm considering using the "average day" for each month, which would remove the problem of months having different days. So for example, February data is represented by the average Feb day - the minimum temperature, maximum temp, mean temp, number of hours above/below certain thresholds. Does this sound okay? @oremnirv

**Comment by oremnirv** [comment]
@michellewl depends if we are predicting total usage. If so, I think #days is still highly informative
