### ISSUE TITLE
transform 'meter reading' --> meter reading / sqrft

### ISSUE THREAD

**Issue by oremnirv** [michellewl/building_resilience#47]

**Comment by oremnirv** [comment]
In my branch there is a formatting.py script for that

**Comment by oremnirv** [comment]
@michellewl Can you see if you can use it? Thanks!

**Comment by michellewl** [comment]
I can't seem to find it!

**Comment by oremnirv** [comment]
@michellewl  https://github.com/michellewl/building_resilience/blob/omer/data/formatting.py

**Comment by oremnirv** [comment]
my bad - I didn't say it's under the data folder

**Comment by michellewl** [comment]
Thanks!
